travis:
  secure:
    BINSTAR_TOKEN: wzQJcZfwwAYS2Hs6ryfZJE7KUOA4BunxiB00/6Cgh14KFuPxo1NtnlHoZpH8tkB7tWhZfkmj9wpywGjbmIOdxC6QHzY5FM9JgPLIX61+fGsnRo9qJ/A9s3o8j9MCM3zWFB+HPRuw0CW0Bm/FtUfqet/7OTIO4cfFNuYs60Lm5LIp3y9jU7R+sdBgAK7jApxZUdWiTxOYOJ1H5xIai8a4Ak5A9rfflmAYb/G1nZ0H27P8vks6BzAYs9Ag3Qv/Jq/LBEjYcG58H13RgBOpXb9xftSyUf6f49Z8BypVhDGvqRSVOl1wofMIXL8c0hin3QCavfREwlD8C4BAARE2epJtGZN6EYhjQltntq5sWhYf4gi4t4O/zt1byZ/fY3oitl7GESr6lm5aC/uf6yla81apWKiqnVWFMGgagHEDG+wacQWeqIfmUcoKehu+5SIEY+N5+962q6zJ+vkS5xpvKo9CqHVvwj8ImaON1GxhDmLIGliCLDnM3TlJQTndI1l+aq/5XhUZ4wVuiFFdZD41c+kyLzlo+gV/jb3veyrDWU4F0bFVixa/TA/fPIniJeIWnhkUORI5H6yc3dcRb2DgdjljU64Xb9uUPhGikz9d+p9U1uWer/HQpCkFI8hb4PYh4LdW5c4x1N8nCrtnJjKJeS8XWk+iUXsBzuYM2LwnQu7foe4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
